/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Voting {
      
    export type CandidateStruct = {id: BigNumberish, name: string, party: string, symbol: string, description: string, voteCount: BigNumberish, exists: boolean, active: boolean}

    export type CandidateStructOutput = [id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean] & {id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "candidateCount" | "candidates" | "disableCandidate" | "editCandidate" | "electionEnded" | "electionStarted" | "endElection" | "getAllCandidates" | "getCandidate" | "hasAddressVoted" | "hasVoted" | "isNullifierConsumed" | "owner" | "startElection" | "vote" | "voteWithCommitment"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BallotCast" | "CandidateAdded" | "CandidateDisabled" | "CandidateUpdated" | "ElectionEnded" | "ElectionStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [string, string, string, string]): string;
encodeFunctionData(functionFragment: 'candidateCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'disableCandidate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'editCandidate', values: [BigNumberish, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'electionEnded', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionStarted', values?: undefined): string;
encodeFunctionData(functionFragment: 'endElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllCandidates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasAddressVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isNullifierConsumed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'startElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voteWithCommitment', values: [BytesLike, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidateCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disableCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'editCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionEnded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionStarted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAddressVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isNullifierConsumed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteWithCommitment', data: BytesLike): Result;
  }

  
    export namespace BallotCastEvent {
      export type InputTuple = [ballotCommitment: BytesLike, candidateId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [ballotCommitment: string, candidateId: bigint, timestamp: bigint];
      export interface OutputObject {ballotCommitment: string, candidateId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CandidateAddedEvent {
      export type InputTuple = [candidateId: BigNumberish, name: string, party: string];
      export type OutputTuple = [candidateId: bigint, name: string, party: string];
      export interface OutputObject {candidateId: bigint, name: string, party: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CandidateDisabledEvent {
      export type InputTuple = [candidateId: BigNumberish];
      export type OutputTuple = [candidateId: bigint];
      export interface OutputObject {candidateId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CandidateUpdatedEvent {
      export type InputTuple = [candidateId: BigNumberish, name: string, party: string];
      export type OutputTuple = [candidateId: bigint, name: string, party: string];
      export interface OutputObject {candidateId: bigint, name: string, party: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionEndedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionStartedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_name: string, _party: string, _symbol: string, _description: string, ],
      [void],
      'nonpayable'
    >
    

    
    candidateCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, boolean, boolean] & {id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean }],
      'view'
    >
    

    
    disableCandidate: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    editCandidate: TypedContractMethod<
      [_candidateId: BigNumberish, _name: string, _party: string, _symbol: string, _description: string, ],
      [void],
      'nonpayable'
    >
    

    
    electionEnded: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    electionStarted: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getAllCandidates: TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >
    

    
    getCandidate: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, boolean, boolean] & {id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean }],
      'view'
    >
    

    
    hasAddressVoted: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isNullifierConsumed: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    startElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    voteWithCommitment: TypedContractMethod<
      [_ballotCommitment: BytesLike, _nullifierHash: BytesLike, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, _party: string, _symbol: string, _description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'candidateCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, boolean, boolean] & {id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'disableCandidate'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'editCandidate'): TypedContractMethod<
      [_candidateId: BigNumberish, _name: string, _party: string, _symbol: string, _description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'electionEnded'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'electionStarted'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllCandidates'): TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, boolean, boolean] & {id: bigint, name: string, party: string, symbol: string, description: string, voteCount: bigint, exists: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'hasAddressVoted'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isNullifierConsumed'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'startElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteWithCommitment'): TypedContractMethod<
      [_ballotCommitment: BytesLike, _nullifierHash: BytesLike, _candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BallotCast'): TypedContractEvent<BallotCastEvent.InputTuple, BallotCastEvent.OutputTuple, BallotCastEvent.OutputObject>;
getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'CandidateDisabled'): TypedContractEvent<CandidateDisabledEvent.InputTuple, CandidateDisabledEvent.OutputTuple, CandidateDisabledEvent.OutputObject>;
getEvent(key: 'CandidateUpdated'): TypedContractEvent<CandidateUpdatedEvent.InputTuple, CandidateUpdatedEvent.OutputTuple, CandidateUpdatedEvent.OutputObject>;
getEvent(key: 'ElectionEnded'): TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
getEvent(key: 'ElectionStarted'): TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;

    filters: {
      
      'BallotCast(bytes32,uint256,uint256)': TypedContractEvent<BallotCastEvent.InputTuple, BallotCastEvent.OutputTuple, BallotCastEvent.OutputObject>;
      BallotCast: TypedContractEvent<BallotCastEvent.InputTuple, BallotCastEvent.OutputTuple, BallotCastEvent.OutputObject>;
    

      'CandidateAdded(uint256,string,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'CandidateDisabled(uint256)': TypedContractEvent<CandidateDisabledEvent.InputTuple, CandidateDisabledEvent.OutputTuple, CandidateDisabledEvent.OutputObject>;
      CandidateDisabled: TypedContractEvent<CandidateDisabledEvent.InputTuple, CandidateDisabledEvent.OutputTuple, CandidateDisabledEvent.OutputObject>;
    

      'CandidateUpdated(uint256,string,string)': TypedContractEvent<CandidateUpdatedEvent.InputTuple, CandidateUpdatedEvent.OutputTuple, CandidateUpdatedEvent.OutputObject>;
      CandidateUpdated: TypedContractEvent<CandidateUpdatedEvent.InputTuple, CandidateUpdatedEvent.OutputTuple, CandidateUpdatedEvent.OutputObject>;
    

      'ElectionEnded(uint256)': TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
      ElectionEnded: TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
    

      'ElectionStarted(uint256)': TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
      ElectionStarted: TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
    
    };
  }